---
# tasks file for edunham.xcode

- name: Test whether Xcode DMG was uploaded earlier
  stat: path="/Users/{{ ansible_ssh_user }}/{{ xcode_dmg }}"
  register: xcode_dl_path

- name: Upload Xcode DMG to the host
  copy: 
      src={{ xcode_dmg }}
      dest=/Users/{{ ansible_ssh_user }}
  when: xcode_dl_path.stat.exists == False

- name: Mount the Xcode DMG with hdiutil
  command: hdiutil attach /Users/{{ ansible_ssh_user }}/{{ xcode_dmg }}
  args:  
      creates: /Volumes/Xcode/

- name: Install Xcode
  command: cp -r /Volumes/Xcode/Xcode.app /Applications/
  args:
      creates: /Applications/Xcode.app/

- name: Upload Command Line Tools DMG to the host
  copy: 
      src={{ cmdline_tools_dmg }}
      dest=/Users/{{ ansible_ssh_user }}

- name: Mount the Command Line Tools with hdiutil
  command: hdiutil attach /Users/{{ ansible_ssh_user }}/{{ cmdline_tools_dmg }}
  args:
      creates: /Volumes/Command\ Line\ Developer\ Tools/

- name: Install the Command Line Tools
  command: sudo installer -pkg /Volumes/Command\ Line\ Developer\ Tools/ -target /  

