---
# tasks file for edunham.xcode

- name: Test whether Xcode DMG was uploaded earlier
  stat: path="/Users/{{ ansible_ssh_user }}/{{ xcode_dmg }}"
  register: xcode_dl_path

- name: Upload Xcode DMG to the host
  copy: 
      src={{ xcode_dmg }}
      dest=/Users/{{ ansible_ssh_user }}
  when: xcode_dl_path.stat.exists == False

- name: Mount the Xcode DMG with hdiutil
  command: hdiutil attach /Users/{{ ansible_ssh_user }}/{{ xcode_dmg }}
  args:  
      creates: /Volumes/Xcode/

- name: Install Xcode
  command: cp -r /Volumes/Xcode/Xcode.app /Applications/
  args:
      creates: /Applications/Xcode.app/
